### ISSUE TITLE
Group the resources by type

### ISSUE THREAD

**Issue by nucliweb** [imteekay/web-performance-research#8]
What do you think about group the resources by type?

**e.g.**
```md
### Videos
...

### Articles
...

### Resource 
...
```

**Comment by imteekay** [comment]
Before I built it with markdown tables and one of the columns was the type of content (video/article/paper/etc). It started to get difficult to manage the rows so I replace them with plain links.

Now, this repo has the problem of not knowing if the resource/link is a video, article, or any type of content.

Although your idea is super valid, I also group them by a more granular topic like in the [core-web-vitals](https://github.com/imteekay/web-performance-research/tree/master/core-web-vitals), where I separate the links by topic types: CLS, LCP, etc. In [measuring-performance](https://github.com/imteekay/web-performance-research/tree/master/measuring-performance), I also have granular topics like tools, benchmark, runtime perf, more general resources, etc.

So, I started to think if it would be easy to understand the type of content by an icon, like in the [sustainability](https://github.com/imteekay/web-performance-research/tree/master/sustainability) category. I also thought of adding a `[topic]` at the beginning of each link too, like [[Article] Website performance and the planet](https://blog.webpagetest.org/posts/website-performance-and-the-planet).

I'm open to discussing it.
